// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAxCIgVUkAmmVbcOwQxobtjF3FYU4z57c',
    appId: '1:1037935959030:web:3c9d22e38a25fd77bf05d7',
    messagingSenderId: '1037935959030',
    projectId: 'iambiz-3568f',
    authDomain: 'iambiz-3568f.firebaseapp.com',
    storageBucket: 'iambiz-3568f.firebasestorage.app',
    measurementId: 'G-LPY4MXLLP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQLXRqPVw9BOlj2OxqW9mDkawjp_A1DRI',
    appId: '1:1037935959030:android:c6a2fb17a20d9235bf05d7',
    messagingSenderId: '1037935959030',
    projectId: 'iambiz-3568f',
    storageBucket: 'iambiz-3568f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ6h5RtkCy3cmrlsg8J2ax8Z6Y2l56Qwg',
    appId: '1:1037935959030:ios:e7486d56496cd18cbf05d7',
    messagingSenderId: '1037935959030',
    projectId: 'iambiz-3568f',
    storageBucket: 'iambiz-3568f.firebasestorage.app',
    iosBundleId: 'com.example.iambiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ6h5RtkCy3cmrlsg8J2ax8Z6Y2l56Qwg',
    appId: '1:1037935959030:ios:e7486d56496cd18cbf05d7',
    messagingSenderId: '1037935959030',
    projectId: 'iambiz-3568f',
    storageBucket: 'iambiz-3568f.firebasestorage.app',
    iosBundleId: 'com.example.iambiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAxCIgVUkAmmVbcOwQxobtjF3FYU4z57c',
    appId: '1:1037935959030:web:ea1f822b5d3c433dbf05d7',
    messagingSenderId: '1037935959030',
    projectId: 'iambiz-3568f',
    authDomain: 'iambiz-3568f.firebaseapp.com',
    storageBucket: 'iambiz-3568f.firebasestorage.app',
    measurementId: 'G-7HK3RE9ZQ6',
  );
}
